# Generated by Django 2.0.5 on 2018-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180602_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='genres',
            field=models.ManyToManyField(to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='author',
            name='languages',
            field=models.ManyToManyField(to='catalog.Language'),
        ),
    ]
