# Generated by Django 2.0.5 on 2018-06-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180603_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_list_all_borrowed', 'List all borrowed books'))},
        ),
    ]
