# Generated by Django 2.0.5 on 2018-06-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180604_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_list_all_borrowed', 'List all borrowed books'), ('can_renew', 'Renew issued books'))},
        ),
    ]
