# Generated by Django 2.0.5 on 2018-06-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180604_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_list_all_borrowed', 'List all borrowed books'), ('can_return', 'Return issued books'), ('can_renew', 'Renew issued books'))},
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='fine',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
